### ISSUE TITLE
Amazon cloud player doesn't have a debian dependency on flash

### ISSUE THREAD

**Issue by hexmode** [tiliado/nuvola-app-amazon-cloud-player#10]
I ran into a problem with the player not starting up, so I began removing plugins.

I was able to uninstall flash without any complaint, but when I logged in to the player, it told me I needed to install flash.  After installing flash it worked again.

By the way the conflicting packages that appeared to make the player break were gecko-mediaplayer and icedtea-7-plugin.

**Comment by hexmode** [comment]
ping @fenryxo and @SteVwonder (not sure I need to do that, but just in case.)

**Comment by jiri-janousek** [comment]
Hi @hexmode. Thanks for reporting this issue. Indeed, Nuvola Player currently only recommends the Flash plugin but it should depend on it. Individual services don't have own dependencies yet (tiliado/nuvolaplayer#158).

**Comment by jiri-janousek** [comment]
Hello @hexmode. Nuvola is in progress to move to flatpak packages, so I'm closing this issue as obsolete.

**Comment by hexmode** [comment]
What does that mean?

**Comment by jiri-janousek** [comment]
No improvement for Debian/Ubuntu/Fedora packaging is planned as the next stable release Nuvola 4.0 will be available only as [cross-distribution flatpak packages](https://dl.tiliado.eu/nuvola-apps/). DEB/RPM packages are going to be discontinued.
