### ISSUE TITLE
Songbar not changing 

### ISSUE THREAD

**Issue by MaSven** [tiliado/nuvola-app-amazon-cloud-player#12]
To reproduce
- Make a list of songs
- Spring to the last song
- Skip to the last second of the song
- now double tap on a song to play it
- The songbar will now show only the last song of the List and seconds will hold at -1 

Amazon-Player version 5.1 Nuvola-Player version 3.0.0
![amazonbug](https://cloud.githubusercontent.com/assets/9138252/14463455/5e3adaec-00cb-11e6-87c6-8c3d901519c3.png)

**Comment by jiri-janousek** [comment]
Hello @Eiamnacken. Thanks for taking the time to report this issue. I need more information to investigate it further. Could you provide information about your system? See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#your-system) for details.

**Comment by jiri-janousek** [comment]
Hello @Eiamnacken. I'm closing this issue as I haven't received any response to my request for more information I posted on April 14th, 2016. If the issue still persists, feel free to add missing information and reopen this ticket.
