### ISSUE TITLE
Nuvola does not recognise the current song 

### ISSUE THREAD

**Issue by lonlazer** [tiliado/nuvola-app-amazon-cloud-player#17]
Nuvola does not recognise the current song. It shows in the sidebar only (null). So neither the lyrics plugin nor the desktop notifications are working.

I installed the Version 5.1 of the Plugin and Version 3.1.0 of Nuvola via the Arch User Repository.

![screenshot_20160724_004057](https://cloud.githubusercontent.com/assets/19411776/17080677/06871d16-5138-11e6-9c19-b5dfcfd5b971.png)

**Comment by jiri-janousek** [comment]
Hello @lonlazer. Thanks for taking the time to report this issue. I can confirm it.

@SteVwonder, could you take care of it? Thanks!

**Comment by dskbrd** [comment]
I wonder if there is still someone taking care of updating this service/app. 
Can someone give us some information about it?
@fenryxo @SteVwonder

**Comment by jiri-janousek** [comment]
Hello @das-keyboard. This script is currently unmaintained as the maintainer @SteVwonder seems to have lost interest in it. I might take over it next month if there is any spare time.

**Comment by jiri-janousek** [comment]
I've adopted this abandoned script and released version 5.2 with fixes.

-- Jiri Janousek, Nuvola Player developer • _My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/). [:heart: Make a donation](https://tiliado.eu/nuvolaplayer/funding/) to keep the project going. Thank you._
