### ISSUE TITLE
High CPU consumption with maximized window

### ISSUE THREAD

**Issue by Hibbo** [tiliado/nuvola-app-amazon-cloud-player#19]
Using Nuvola 3.0.3 with as Amazon Cloud Player (5.1) on Fedora 24.

CPU consumes around 80% when windows in brought to front.
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+  
25024 cfi       20   0 3510156 346200  44684 R  82.8  4.4  25:05.61 WebKitWebProces  
25067 cfi       20   0 2324700  35440  12420 S  13.6  0.5  14:04.48 WebKitPluginPro  
25008 cfi       20   0 3019132  29968  22172 S   5.0  0.4   3:37.58 nuvolaplayer3-a  

Network Library: libsoup 2.54.1
Web Engine: WebKitGTK 2.12.4

Window minimized is using between 8-10% CPU.

uname -a
Linux cfi-tp 4.7.3-200.fc24.x86_64 #1 SMP Wed Sep 7 17:31:21 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz

**Comment by jiri-janousek** [comment]
Hello @Hibbo. Thanks for taking the time to report this issue. I need more information to investigate it further.
- Do you use the default desktop theme?
- Is the issue reproducible also in the GNOME Web browser (previously called Epiphany) and the Amazon Cloud Player website?
- What graphic card do you use?

**Comment by Hibbo** [comment]
Hi, 
I am using Cinnamon as DE:
cinnamon.x86_64                         3.0.7-1.fc24 
theme "Android Holo".

Its iGPU Intel HD Graphics 4400.

Gnome browser is not installed, whats the name of the package?

**Comment by jiri-janousek** [comment]
> theme "Android Holo".

Does the issue persist if you select the default Cinnamon theme?

> Gnome browser is not installed, whats the name of the package?

Probably epiphany.

**Comment by Hibbo** [comment]
No difference with standard theme.

I installed epiphany and can observe same CPU consumption:

```
zsh> top
 7305 cfi       20   0 3389756 565112 137512 R  86.5  7.2   0:34.91 WebKitWebProces
 7380 cfi       20   0 2398056  74284  48168 S  22.1  0.9   0:03.42 WebKitPluginPro   
```

```
zsh> ps -fax
 5935 ?        Ssl    0:04  \_ /usr/libexec/gnome-terminal-server
 5941 pts/0    Ss     0:00  |   \_ zsh
 7288 pts/0    Sl+    0:09  |   |   \_ epiphany
 7626 pts/1    Ss     0:00  |   \_ zsh
 7978 pts/1    R+     0:00  |       \_ ps -fax
 7296 pts/0    Sl+    0:08  \_ /usr/libexec/webkit2gtk-4.0/WebKitNetworkProcess 15
 7305 pts/0    Sl+    1:28  \_ /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 21
 7380 pts/0    Sl+    0:20  \_ /usr/libexec/webkit2gtk-4.0/WebKitPluginProcess2 24 /usr/lib64/mozilla/plugins/libflashplayer.so
```

**Comment by jiri-janousek** [comment]
Could you check out whether the issue happens in Nuvola Player 3.0.4 released a few days ago?

**Comment by Hibbo** [comment]
Yes, updated already, same result.

Frontwindow: ~90% CPU
Backwindow: 30-40% CPU
for WebKitWebProces process.

**Comment by jiri-janousek** [comment]
> Yes, updated already, same result.

So it isn't the bug I thought it could be (tiliado/nuvolaplayer#245).

> I installed epiphany and can observe same CPU consumption.

Since the issue occurs also in Epiphany, I suspect there might a bug in the WebKitGTK library. Could you [report the issue upstream](http://goo.gl/TcsBMf) and post a link to the your bug report here? Thanks.

**Comment by Hibbo** [comment]
Webkit Bug ID https://bugs.webkit.org/show_bug.cgi?id=162264

**Comment by jiri-janousek** [comment]
Thanks @Hibbo.

**Comment by jiri-janousek** [comment]
Is the issue still reproducible with Nuvola 3.0.7 and a recent WebKitGTK?

**Comment by jiri-janousek** [comment]
A month without a response, closing.
