### ISSUE TITLE
Update to comply with Service Integration Guidelines

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvola-app-amazon-cloud-player#21]
Hello @a-m-s. We have [Guidelines for scripts](https://tiliado.github.io/nuvolaplayer/development/apps/guidelines.html). I forget to mention them before but they have been just recently updated anyway. There were a few mistakes in your recent commits. Could you fix them? Thanks!

* c65b3da - It is necessary to [update changelog (CHANGELOG.md)](https://tiliado.github.io/nuvolaplayer/development/apps/guidelines.html#changelog). Add a new subheading `5.4 - unreleased` and then a bullet point `New maintainer: ...`.
* 05fc43dfe12e - Don't increase version number in metadata.json, that's done in [special release commits](https://tiliado.github.io/nuvolaplayer/development/apps/guidelines.html#releases). Also, append a new entry to the changelog for the `5.4 - unreleased` subheading.
* Then you can create the release commit for the 5.4 release. There are [some rules](https://tiliado.github.io/nuvolaplayer/development/apps/guidelines.html#releases) for that as well. It is, however, easier to just create a new ticket `Release 5.4` and assign it to me. That's the preferred way to notify me I should rebuild packages.

**Comment by a-m-s** [comment]
Done, I think.
