### ISSUE TITLE
Amazon Music Playlists not playing on Linux Mint

### ISSUE THREAD

**Issue by macmike** [tiliado/nuvola-app-amazon-cloud-player#23]
Last week, it was working perfectly, this week I can play individual songs from the My Music sognlist but can't view several Amazon Music pages such as Home, Recommended or my playlists. Selecting these pages brings the loading swirly in the main tab but nothing ever resolves.

I've tried turning the flash settings on and off again.

I'm running Linux Mint 17 64 bit nuvola v5.2 0 there's no errors in the console.

**Comment by a-m-s** [comment]
5.2 is the Amazon plugin version. What version of Nuvola Player do you have?

Can you try the most recent Amazon plugin? It's version 5.4.

**Comment by macmike** [comment]
I'm running nuvola v3.08 - I'll try updating the plugin...

**Comment by macmike** [comment]
I'm getting the same behaviour on amazon plugin v5.4

**Comment by a-m-s** [comment]
There's three things that might have changed: Nuvola, WebKit, and the
Amazon website. It's all still working for me. Please check your apt logs
and see if anything changed for you.

You can also check if it works in Epiphany (a.k.a. Gnome "Web")? Both
Epiphany and Nuvola use the same WebKit, so it'll be a good clue (probably,
I don't actually use Mint so I can't be sure). If that doesn't work, and
Webkit was recently updated, then try rolling back Webkit and see if that
helps.

Future versions will use Flatpak to bundle known-good Webkit and solve this
problem. You can try the beta version if you have a suitable tiliado
account.

**Comment by macmike** [comment]
Thanks for your help. I can confirm that Amazon Music works in Amazon web player in FireFox, Chrome and Epiphany/Web. 
Which of the many webkit packages should I downgrade? Synaptic lists 124 with the "webkit" filter?

**Comment by jiri-janousek** [comment]
Hello @macmike. Nuvola developer here. Thanks for taking the time to report this issue. I was able to reproduce it and managed to get rid of it by purging WebKitGTK+ cache, local storage and friends. There is no button for that in Nuvola yet (tiliado/nuvolaplayer#331) but you can do in with [a few commands](https://github.com/tiliado/nuvolaplayer/blob/master/tools/clean_app.sh).

First of all, log out and log in to be sure no WebKitGTK+ applications are running, then run:

```
APP_ID="amazon_cloud_player"
rm -rf ~/.local/share/webkitgtk ~/.cache/webkitgtk
rm -rf ~/.local/share/webkit  ~/.cache/webkit
rm -rf ~/.cache/nuvolaplayer3/webcache ~/.cache/nuvolaplayer3/WebKitCache
rm -rf ~/.local/share/nuvolaplayer3/apps_data/$APP_ID
rm -rf ~/.cache/nuvolaplayer3/apps_data/$APP_ID
rm -rf ~/.config/nuvolaplayer3/apps_data/$APP_ID
```

Let me know whether it helps.

**Comment by macmike** [comment]
Hi @fenryxo - thanks for the tip. I did as you suggested but it didn't work :( It did clear my cache as I had to log in to AMU again, but I still can't see the content frame for playlists/home/recommended etc. although the filters under "My Music" (songs, artists, genres etc.) work as before.

**Comment by a-m-s** [comment]
Maybe you can see if there's some other config/cache trouble by setting HOME to some empty directory and trying again?

env HOME=/tmp/empty nuvolaplayer3

**Comment by jiri-janousek** [comment]
Could you also attach [a complete debugging output](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output)?

**Comment by macmike** [comment]
I appreciate the help here folks - thankyou.

@a-m-s good idea - no change on a clean profile dir

But, I may be onto something... I tried running Amazon Music from the webkit minibrowser (/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/MiniBrowser) and got an error:

> Required plugin could not be found
> 
> MiniBrowser requires to install plugins to play media files of the following type: text/html decoder 

and in console:

> (gstreamer-codec-install:12976): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:997:2: Missing name of pseudo-class
> No handlers could be found for logger "sessioninstaller"
> *** Error in `/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess': double free or corruption (fasttop): 0x00000000026bdf20 ***
> CRITICAL:Could not find any packages to operate on

which I assume means this is a webkit issue rather than a nuvola issue? I think my webkit is borked!

@fenryxo debug log attached. I loaded the app, which was previously on my "Five Star" playlist, moved to "songs" (there's a minified exception at this point but it loads and works) then navigated back to my playlist (doesn't load, no messages I could see) then closed the app.
[nuvola_log.txt](https://github.com/tiliado/nuvola-app-amazon-cloud-player/files/971965/nuvola_log.txt)

**Comment by jiri-janousek** [comment]
Oh, sorry, I've just realized that the Linux Mint version you use (17) is not the latest one (18). That explains a lot. It contains ancient WebKitGTK that  contains a) an awful lot of security vulnerabilities b)  bugs that prevent some pages from working properly. I should have stopped building packages for these old systems a long ago (let's do that asap tiliado/nuvolaplayer#333). I recommend upgrading your system to LM 18. 

This is probably the cause: `Runner: https://images-eu.ssl-images-amazon.com/images/G/01/digital/music/player/web/assets/201732719933268/digitalMusicWebPlayer._CB510660637_.js:2:25198: CONSOLE ERROR Error creating Root ractive TypeError: undefined is not an object (evaluating 'e.TYPED_ARRAY_SUPPORT=void 0!==n.TYPED_ARRAY_SUPPORT?n.TYPED_ARRAY_SUPPORT:i()')`

**Comment by macmike** [comment]
Thanks :) I'll upgrade!
