### ISSUE TITLE
metadata for add-on packages

### ISSUE THREAD

**Issue by martinkg** [tiliado/nuvola-app-amazon-cloud-player#24]
Since this is add-on package, it should contain add-on metadata [1]. This way, Gnome Software will be able to list this add-on side by side with Nuvola player, which is pretty convenient.

[1]: https://fedoraproject.org/wiki/Packaging:AppData#.metainfo.xml_file_creation

I have added a metainfo.xml file, that should copied to /usr/share/appdata/nuvola-app-amazon-cloud-player.metainfo.xml
[nuvola-app-amazon-cloud-player.metainfo.xml.txt](https://github.com/tiliado/nuvola-app-amazon-cloud-player/files/1044959/nuvola-app-amazon-cloud-player.metainfo.xml.txt)

**Comment by jiri-janousek** [comment]
Issue moved to [tiliado/nuvolasdk #1](https://github.com/tiliado/nuvolasdk/issues/1) via [**ZenHub**](https://www.zenhub.com/)
