### ISSUE TITLE
Are the nuvolaplayer3_amazon_cloud_player.* icons required?

### ISSUE THREAD

**Issue by martinkg** [tiliado/nuvola-app-amazon-cloud-player#26]
Are the nuvolaplayer3_amazon_cloud_player.* icons required?
- I am not sure the icons located in %{_datadir}/icons/*/*/*
/nuvolaplayer3_amazon_cloud_player.* are required. The .desktop file specifies they should be named eu.tiliado.NuvolaAppAmazonCloudPlayer, which is the other set available.

**Comment by jiri-janousek** [comment]
They are needed by Nuvola 3.0 and they are still used in the internal icon loading code of Nuvola 4, which is going to change - tiliado/nuvolaruntime#353
