### ISSUE TITLE
"Flash blocked" error for Prime streaming

### ISSUE THREAD

**Issue by thw0rted** [tiliado/nuvola-app-amazon-cloud-player#28]
I'm trying to use the Cloud Player module to listen to Prime streaming music.  I'm on Ubuntu 16.04.  I was unable to do it in Chromium, which I'm told may be because of the DRM Amazon is trying to use.  I was hoping that the version of Flash that Nuvola uses might be different, but it looks like that's not the case.  I get this:

![image](https://user-images.githubusercontent.com/943160/28708840-fb6b92e0-737d-11e7-8777-7b53ccfff5bb.png)

Of course, Flash is actually enabled, but the error message may actually mean that the *version* of Flash in use doesn't support the DRM they want.  For reference:

![image](https://user-images.githubusercontent.com/943160/28708877-23b2ef14-737e-11e7-8ded-0c7eb2f1da30.png)

**Comment by jiri-janousek** [comment]
Hello @thw0rted. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Which [version of Nuvola player](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#your-nuvola-player-instance) do you use?
* The debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output).

**Comment by thw0rted** [comment]
The player is release 3.0.9 installed from the Xenial repository (f79856a).  When I attempted to reproduce the issue, the player started working -- I don't think I made any changes or installed anything new.  So, I guess you can close this and I'll report back in if it happens again.  Thanks!

**Comment by thw0rted** [comment]
Actually, hold the phone, it broke again.  This is very strange.

I played a song, and it worked, but the interface language was not what I wanted (I live in Germany but my German is not great).  So, I scrolled down to my name, and clicked to change settings (Einstellungen in German).  This opened a new window with my account prefs, and here I was able to switch to English.  After I did that I closed the settings window and refreshed the player window using the context menu -> refresh.  Now, I picked an album to listen to and it showed the same "Flash Blocked" popup.

I believe the debug log was running the whole time.  I'm attaching it now.
[debuglog.txt](https://github.com/tiliado/nuvola-app-amazon-cloud-player/files/1182528/debuglog.txt)

...aaaand now it's working again.  I quit the player before uploading the debug output.  Then I launched it again, on the hunch that maybe "stations" worked but "albums" don't, and playing an album *or* station worked fine.

**Comment by jiri-janousek** [comment]
> After I did that I closed the settings window and refreshed the player window using the context menu -> refresh. Now, I picked an album to listen to and it showed the same "Flash Blocked" popup.

Unfortunately, there is no page refresh in the log. Could you try to reproduce the issue again and collect new debug log?

**Comment by thw0rted** [comment]
Sorry it's taken so long to get back, I've tried this several more times but can't seem to reproduce when the debug log is running.  I'll post back here if I actually manage to capture the failure.

**Comment by jiri-janousek** [comment]
My guess is that the issue is caused by tiliado/nuvolaruntime#354. Flash loads fine for the first time but than fails every time a page is reloaded or a new page is loaded. Nuvola 4.5 contains workaround for this bug.
