### ISSUE TITLE
Album name extraction not working

### ISSUE THREAD

**Issue by no-preserve-root** [tiliado/nuvola-app-amazon-cloud-player#30]
The selection for the album name does not work (anymore?). As a result, the album name `(null)` is rendered in the sidebar.

Current selector is
```
elm = document.querySelector('tr.currentlyPlaying td.albumCell');
track.album = elm ? elm.title : null;
```
Working selector is
```
elm = document.querySelector("#dragonflyTransport .trackSourceLink a");
track.album = elm ? elm.textContent : null;
```

Using nuvola and integrations from AUR.
```
$ nuvola --version
Web Apps - based on Nuvola Apps™ project
Version 4.9.0
Revision snapshot
Diorite 4.9.0
WebKitGTK 2.18.5
libsoup 2.60.2
```
Amazon Cloud Player integration version is 5.5.

**Comment by a-m-s** [comment]
Confirmed; I see the missing name too, now.

**Comment by a-m-s** [comment]
@no-preserve-root thanks for the patch!
