### ISSUE TITLE
Looking for Something? We're sorry. The Web address you entered is not a functioning page on our site. 

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvola-app-amazon-cloud-player#37]
Hello @a-m-s. This is only an informational bug report because the user has resolved the issue without providing any logs, so we cannot investigate it further and possibly fix it. However, It could happen to another user so let's document the issue here.

The user:

> Since I activated Nuvola, each time I start my actual player App
(Amazon Cloud Player), it first brings up the following error page:
>
> Looking for Something?
We're sorry. The Web address you entered is not a functioning page on
our site. Please double-check the URL for typos and other errors. Or go
to our home page.
>
> When I click the link "home page", however, I am redirected to the
actual amazon music page.
>
> Have you got any idea what could be the problem? I've been running the
same setup now for months successfully here on my openSuse tumbleweed.
I've installed Nuvola and the AmazonCloud Player app via the flatpak
commands listed on the nuvola pages. It seems that something is wrong
now after the activation.

Me:

> It is more likely to be caused by a change on Amazon website rather
the by the activation. Could you create a bug [link] report following the
guidelines at [link]?

The user:

> The problem persisted until today. The way I solved it was as follows:
I clicked on the menu button and then "Load URL...". From the non-
working URL displayed there, I removed the cryptic album identifier and
loaded the page that was pointed to by the remainder. That worked.
After Quitting Nuvola and restarting it, everything worked fine. So it
seemed something was was wrong with the last URL Nuvola remembered from
before I activated it. However, I have no idea what the activation
exactly messed up. At least, I found an easy way to fix it.

**Comment by a-m-s** [comment]
Sounds like just clicking the home button would have worked too. Odd bug though.
