### ISSUE TITLE
Feature Request: Add India in Amazon Cloud Player country selection

### ISSUE THREAD

**Issue by ajithrn** [tiliado/nuvola-app-amazon-cloud-player#40]
Currently there is no option to select India as a national variant in amazon cloud player. Amazon India used a .in domain  for its service [https://music.amazon.in/](https://music.amazon.in/) If you can add the support for it that would be great.

**Comment by a-m-s** [comment]
Thanks for the pull request. I added tested it and added a changelog entry.

**Comment by jiri-janousek** [comment]
New flatpaks were published - Amazon Cloud Player 5.9.5.
