### ISSUE TITLE
Feature Request: Add Brazil support

### ISSUE THREAD

**Issue by eduardoweiland** [tiliado/nuvola-app-amazon-cloud-player#43]
Amazon Music in Brazil uses domain music.amazon.com.br

**Comment by jiri-janousek** [comment]
Hello @eduardoweiland. @a-m-s has added support for Brazil. I'm still struggling with tiliado/nuvola-flatpaks#1. I will publish new flatpaks once it is resolved.

**Comment by eduardoweiland** [comment]
Thanks @fenryxo and @a-m-s

**Comment by jiri-janousek** [comment]
New flatpaks have been published.
