### ISSUE TITLE
Unity no background play and no integration with indicator

### ISSUE THREAD

**Issue by JulienGAMartin** [tiliado/nuvola-app-amazon-cloud-player#7]
Hi
the player stopped is the main window closed even when the option play in the background is checked.
No notifications
No integration with Ubuntu sound indicator
Quicklist in Unity is greyed out and not available.
Control options (play, stop,...) in the menu and HUD are also greyed out and not available
Amazon Cloud Player v 5.0
Ubuntu 15.10

**Comment by jiri-janousek** [comment]
Hello @martinjuju. Thanks for taking the time to report this issue. I'm notifying the mainainer of Amazon Cloud Player script.

@SteVwonder, could you take a look at this issue?

**Comment by jiri-janousek** [comment]
Fixed in Amazon Cloud Player script 5.1. Thanks for your bug report.

**Comment by SteVwonder** [comment]
Thanks @fenryxo!  Sorry for the slow response. The end of the semester was absorbing most of my time.  I'm free'd up for a few months now.

**Comment by jiri-janousek** [comment]
Hello @SteVwonder. It is pretty OK you being busy. However, you should respond to e-mails (within a week) to tell me you are busy. Otherwise, I may assume you have abandoned your script and I can remove it from the Nuvola Player repository.
