### ISSUE TITLE
Not working anymore since Amazon updated their player

### ISSUE THREAD

**Issue by bbuhler** [tiliado/nuvola-app-amazon-cloud-player#8]
Since the latest updates to Amazon Prime Music the media-key mapping and song title notifications are not working anymore.

**Comment by jiri-janousek** [comment]
Thanks for taking the time to report this issue. Unfortunately, the maintainer of the Amazon Cloud Player script seems to be too busy lately. I'll probably have to step in and either fix the issue myself or remove the script from supported services.

**Comment by jiri-janousek** [comment]
Fixed in Amazon Cloud Player script 5.1. Thanks for your bug report.

**Comment by bbuhler** [comment]
Thank you for fixing it (:
