### ISSUE TITLE
Amazon Cloud Player doesn't remember session

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvola-app-amazon-cloud-player#9]
A feedback from Mark A. Hershberger @hexmode (a Nuvola Patron):

> Music Player makes me sign in to Amazon each time and doesn't offer to
> remember my password.  It should either get a persistant token, or offer
> to store my username/password in Gnome's keyring.

Hi @SteVwonder, could you verify that Amazon Cloud Player doesn't remember session and always requires you to sign in? If so, does this issue happen also in Firefox and Chrome/Chromium? (GNOME keyring is a separate ticket tiliado/nuvolaplayer#41.)

**Comment by SteVwonder** [comment]
This happens in Nuvola, Firefox, and Chrome.

**Comment by jiri-janousek** [comment]
> This happens in Nuvola, Firefox, and Chrome.

This should be fixed by Amazon. Is there any way an Amazon Cloud Player customer can report bugs or suggestions?

**Comment by SteVwonder** [comment]
After you login, in the bottom left, there is a "Send us feedback" option that pops up when you mouse over your account name.  I sent in my own feedback about the issue.

**Comment by jiri-janousek** [comment]
Great, @SteVwonder, thanks.

**Comment by jiri-janousek** [comment]
Seems ok now.
